# Generated by Django 4.0.2 on 2023-01-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='fetha.Membership', to='fetha.Person'),
        ),
    ]
